version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    volumes:
      - ./inputdata:/backend
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
